### ISSUE TITLE
Игра не готова!

### ISSUE THREAD

**Issue by He4eT** [pot-team/uralgamejam2016#1]
Привет, красавчики!
Как будете готовы показать демку - отписывайтесь тут.
Когда ваши чятики огласит крик "Продакшн!!!1" и вы будете готовы показать финальную версию своего шедевра - тыкайте кнопочку "Закрыть issue."

Удачи вам, жду годноты и возлагаю надежды =)

**Comment by tujhex** [comment]
Архивы с демкой под разные платформы лежат в папке **build**

**Comment by tujhex** [comment]
Быстро, отстойно, архивы лежат в папочке build
Лучше не станет, хуже быть не может
